# Generated by Django 4.2.3 on 2023-07-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="sub_heading",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
