# Generated by Django 4.2.3 on 2023-07-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0003_blog_sub_heading_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="sub_heading",
            field=models.CharField(default="This is Sub Heading", max_length=300),
        ),
    ]
